---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-glaa
spec:
  podSelector:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-internal
      ports:
        - protocol: TCP
          port: 443

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-induction-glaa
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx-internal"
    stable.k8s.psg.io/kcm.class: default
spec:
  tls:
  - hosts:
    - glaa.developer-induction.notprod.acp.homeoffice.gov.uk
    secretName: hello-world-tls
  rules:
  - host: glaa.developer-induction.notprod.acp.homeoffice.gov.uk
    http:
      paths:
        - path: /
          backend:
            serviceName: public
            servicePort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: dev-induction-glaa
spec:
  selector:
    name: dev-induction-glaa
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 11443

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-induction-glaa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dev-induction-glaa
        service: dev-induction-glaa
    spec:
      containers:
      - name: dev-induction-glaa
        image: quay.io/ukhomeofficedigital/dev-induction-glaa:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
        ports:
          - containerPort: 4000
        env:
          - name: MYSUPERSECRET
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: mysupersecret
      - name: nginx
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.0
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
        env:
        - name: PROXY_SERVICE_HOST
          value: 127.0.0.1
        - name: PROXY_SERVICE_PORT
          value: "4000"
        - name: SSL_CIPHERS
          value: ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:AES256+EDH:!aNULL
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: PORT_IN_HOST_HEADER
          value: "FALSE"
        - name: ERROR_REDIRECT_CODES
          value: "599"
        - name: ADD_NGINX_SERVER_CFG
          value: |
            large_client_header_buffers 4 32k;
        - name: ADD_NGINX_LOCATION_CFG
          value: |
            proxy_buffer_size         128k;
            proxy_buffers             4 256k;
            proxy_busy_buffers_size   256k;
        ports:
        - name: https
          containerPort: 11443

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squidproxy-config
data:
  squid.conf: |
    # ACL ALLOWED PORTS
    acl Safe_ports port 443                # HTTPS
    acl SSL_ports port 443                 # HTTPS
    acl CONNECT method CONNECT
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports

    # PID file location
    pid_filename /home/proxy/squid.pid

    # LISTENING PORT
    http_port 4000

    # ADDITIONAL TWEAKS
    cache deny all
    forwarded_for delete
    httpd_suppress_version_string on
    via off

    # LOGGING
    logfile_rotate 0
    logformat squid {"logtime":"%tl", response_time":%tr, "src_ip":"%>a", "squid_request_status":"%Ss", "http_status_code":%>Hs, "reply_size_include_header":%<st, "http_method":"%rm", "request_url":"%ru", "request_path":"%rp", "squid":"%Sh", "dst_ip":"%<a", "content_type":"%mt"}
    cache_log stdio:/dev/stdout
    access_log stdio:/dev/stdout
    cache_store_log stdio:/dev/stdout
  mime.conf: |
    # Empty file

---
apiVersion: v1
data:
  mysupersecret: {{.MY_SECRET}}
kind: Secret
metadata:
  name: my-secret
type: Opaque